# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
enable_free_tier: false
early_access: false
reviews:
  poem: false
  review_details: true
  path_instructions:
    - path: '**/*'
      instructions: |
        - Define what good looks like to you here
        - Be specific. Do not leave room for ambiguity
  path_filters:
    - '!**/*.bin'
    - '!**/*.zip'
    - '!**/*.7z'
    - '!**/*.jar'
    - '!**/*.tar'
    - '!**/*.mp3'
    - '!**/*.jpeg'
knowledge_base:
  code_guidelines:
    filePatterns:
      - "**/CODING_GUIDELINES.md"
