# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
enable_free_tier: false
poem: false
reviews:
    review_details: true
    path_filters:
    - '!**/*.bin'
    - '!**/*.zip'
    - '!**/*.7z'
    - '!**/*.jar'
    - '!**/*.tar'
    - '!**/*.log'
    - '!**/*.mp3'
    - '!**/*.jpeg'
